### ISSUE TITLE
No context menu

### ISSUE THREAD

**Issue by chkd** [xgouchet/Axel#11]
Hello. I try to make app (Android Studio), everything is fine, but the context menu doesn't appear after long pressing on node. And NodeEditorActivity doesn't open after touching. What do I do incorrectly?

**Comment by xgouchet** [comment]
I'm currently in a big refactoring process on this app, so the latest version may not be fully featured. I advise you to use a prior version (anything before July).

**Comment by chkd** [comment]
Thank you!
You should create a branch for development or for the stable version of this app :)

**Comment by xgouchet** [comment]
good idea, I'll do that ASAP
